site_name: CTF Wiki
site_description: CTF Wiki
site_author: CTF Wiki Team
site_url: https://ctf-wiki.org/en/
repo_name: ctf-wiki/ctf-wiki
repo_url: https://github.com/ctf-wiki/ctf-wiki
edit_uri: blob/master/docs/
copyright: Copyright &copy; 2016 - 2021 CTF Wiki Team
theme:
  name: material
  language: en
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: https://ctf-wiki.org/_static/img/logo.png
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  font:
    text: Noto Sans
    code: Source Code Pro
plugins:
- search
- minify:
    minify_html: true
nav:
- Start:
  - index.md
  - contributing.md
- Crypto:
  - 基础数学知识:
    - crypto/basic/introduction.md
  - 古典密码:
    - crypto/classical/introduction.md
    - crypto/classical/summary.md
  - 流密码:
    - crypto/streamcipher/intro.md
    - 伪随机数生成器:
      - crypto/streamcipher/prng/intro.md
      - crypto/streamcipher/special/rc4.md
  - 块加密:
    - crypto/blockcipher/introduction.md
  - 非对称加密:
    - 格密码:
      - crypto/asymmetric/lattice/overview.md
markdown_extensions:
- admonition
- md_in_html
- codehilite:
    guess_lang: false
- def_list
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji ''
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
extra:
  alternate:
  - link: /
    name: zh - 汉语
  - link: /en/
    name: en - English
  copyright: CC BY-NC-SA 4.0
extra_javascript:
- https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
- https://ctf-wiki.org/_static/js/extra.js
- https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
extra_css:
- https://ctf-wiki.org/_static/css/extra.css
