name: Deploy to Netlify

on:
  workflow_run:
    workflows:
      - Build for Netlify
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-netlify:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-for-netlify.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: Build Docs
          persist-credentials: false
          
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: 'site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
