name: Deploy to Netlify

on:
  workflow_run:
    workflows:
      - Build for Netlify
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-netlify:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact Docs
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-for-netlify.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: site-zip
      - name: Unzip Site
        run: |
          rm -rf ./site
          unzip site.zip
          rm -f site.zip
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: 'site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
